### ISSUE TITLE
About StereographicProductManifold

### ISSUE THREAD

**Issue by davendw49** [gatoniel/stereographic-link-prediction#108]
Could you please share the implementation of StereographicProductManifold? 
I am also want to add expmap0 and logmap0 to the product manifold, or could you share the idea or the reference to your implementation?

**Comment by gatoniel** [comment]
Hi, it is implemented in this fork of `geoopt` https://github.com/gatoniel/geoopt
There is a PR that I never finished: https://github.com/geoopt/geoopt/pull/163

**Comment by davendw49** [comment]
Thank you!
